#!/bin/bash

# Complete deployment and sync script
# Usage: ./scripts/deploy-and-sync.sh

set -e  # Exit on error

echo "🚀 Starting complete deployment and sync..."
echo ""

# Step 1: Build contracts
echo "📦 Step 1: Building smart contracts..."
cd sc
forge build
echo "✅ Contracts built successfully"
echo ""

# Step 2: Run tests
echo "🧪 Step 2: Running tests..."
forge test
echo "✅ All tests passed"
echo ""

# Step 3: Deploy to Anvil
echo "🌐 Step 3: Deploying to local network..."
DEPLOYMENT_OUTPUT=$(forge script script/Deploy.s.sol \
  --rpc-url http://127.0.0.1:8545 \
  --broadcast \
  --private-key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 \
  2>&1)

echo "$DEPLOYMENT_OUTPUT"

# Extract addresses from deployment
FORWARDER_ADDRESS=$(echo "$DEPLOYMENT_OUTPUT" | grep "MinimalForwarder deployed at:" | awk '{print $NF}')
DAO_ADDRESS=$(echo "$DEPLOYMENT_OUTPUT" | grep "DAOVoting deployed at:" | awk '{print $NF}')

if [ -z "$FORWARDER_ADDRESS" ] || [ -z "$DAO_ADDRESS" ]; then
  echo "❌ Failed to extract contract addresses"
  exit 1
fi

echo ""
echo "✅ Contracts deployed:"
echo "   MinimalForwarder: $FORWARDER_ADDRESS"
echo "   DAOVoting: $DAO_ADDRESS"
echo ""

# Step 4: Sync ABIs
echo "🔄 Step 4: Syncing ABIs to frontend..."
cd ..
node scripts/sync-abis.js
echo ""

# Step 5: Update .env.local
echo "📝 Step 5: Updating .env.local..."
ENV_FILE="web/.env.local"

# Backup existing .env.local
if [ -f "$ENV_FILE" ]; then
  cp "$ENV_FILE" "$ENV_FILE.backup"
  echo "   Backup created: $ENV_FILE.backup"
fi

# Create or update .env.local
cat > "$ENV_FILE" << EOF
# Auto-generated by deploy-and-sync.sh
# Generated: $(date)

# Contract Addresses
NEXT_PUBLIC_FORWARDER_ADDRESS=$FORWARDER_ADDRESS
NEXT_PUBLIC_DAO_ADDRESS=$DAO_ADDRESS

# Network Configuration
NEXT_PUBLIC_CHAIN_ID=31337
NEXT_PUBLIC_RPC_URL=http://127.0.0.1:8545

# Relayer Configuration (server-side only)
# Using Anvil's second account (index 1)
RELAYER_PRIVATE_KEY=0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d
RELAYER_ADDRESS=0x70997970C51812dc3A010C7d01b50e0d17dc79C8
RPC_URL=http://127.0.0.1:8545
EOF

echo "✅ .env.local updated with new addresses"
echo ""

# Step 6: Summary
echo "🎉 Deployment complete!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 DEPLOYMENT SUMMARY"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ Smart Contracts:"
echo "   MinimalForwarder: $FORWARDER_ADDRESS"
echo "   DAOVoting:        $DAO_ADDRESS"
echo ""
echo "✅ ABIs: Synced to web/lib/abis/"
echo "✅ Environment: Updated in web/.env.local"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🚀 NEXT STEPS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Start the frontend:"
echo "   cd web && npm run dev"
echo ""
echo "2. Open http://localhost:3000"
echo ""
echo "3. Connect MetaMask with Anvil account"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
